spring:
  application:
    name: policy

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/insurance_db
    username: db_user
    password: secret4321!!
