spring:
  application:
    name: policy
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/insurance_db
    username: db_user
    password: secret4321!!

services:
  customer-url: http://localhost:8081

server:
  port: 8082