spring:
  application:
    name: policy

  profiles:
    active: dev

  server:
    port: 8082

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/insurance_db
    username: db_user
    password: secret4321!!

  kafka:
    bootstrap-servers: kafka:29092

    consumer:
      group-id: underwriting-policy-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

services:
  customer-url: http://customer-service:8081